### PR TITLE
Fix focusing hyperlink

### LINKED ISSUE #169: Playwright screenshot is selecting the first hyperlink on the page. It would be nice if it didn't.
politico-2022-06-27T14_08_56 990977-04_00

### PR DESCRIPTION
**Pull request by AsaiToshiya**
Fixed #169.

`headless=False` displays the GUI. As a result, the mouse to focus on a hyperlink.

### CODE REVIEW

**Comment by palewire** [comment]
We have to run headless to use the ad blocker plugin (or really any plugin) so this change isn't available to us.

**Comment by AsaiToshiya** [comment]
Sorry, I did not know that.

The only way I can think of now is to change the style at focus.

**Comment by palewire** [comment]
Not a bad idea!

**Comment by palewire** [comment]
There might be something we can do with this https://playwright.dev/docs/api/class-page#page-focus

**Comment by palewire** [comment]
I've also filed this https://github.com/microsoft/playwright/discussions/15745

**Comment by AsaiToshiya** [comment]
Simply override the style at focus as follows.

politico.js:

```javascript
const style = document.createElement("style");
style.innerHTML = "a:hover { color: initial; }";
document.head.appendChild(style);
```

This works, but must be applied to all sites with problems.

**Pull request closed without merging**
