### PR TITLE
Adds mountain west newspapers workflow

### PR DESCRIPTION
**Pull request by chrislkeller**
Is in conjunction with #12

### CODE REVIEW

**Comment by palewire** [comment]
How would you feel about calling this the "New Mexico" bundle?

**Comment by chrislkeller** [comment]
That works by me...

**Comment by palewire** [comment]
Great. Make that name change to the bundle in each PR and I think we can merge.

**Comment by chrislkeller** [comment]
Closing in favor or new PR coming from a properly forked branch.

**Pull request closed without merging**
