### PR TITLE
Update sources.csv

### PR DESCRIPTION
**Pull request by chrislkeller**
Adds Albuquerque Journal, Albuquerque Business First and Santa Fe New Mexican to source list

### CODE REVIEW

**Comment by palewire** [comment]
Thanks for this. Should abqjournal be in the socal bundle?

**Comment by chrislkeller** [comment]
Good catch. Missed that. I can amend that right?

**Comment by palewire** [comment]
Yep. Just change and push again.

**Comment by chrislkeller** [comment]
Closing in favor or new PR coming from a properly forked branch.

**Pull request closed without merging**
