### PR TITLE
Feature/selector removal

### PR DESCRIPTION
**Pull request by MattieTK**
This adds a new option following the `shot-scraper` documentation to allow custom javascript to be run.

To minimize the effects (and keep the csv readable) I have fixed it to only remove elements listed in the csv, rather than do anything else.

This allows the removal of the kinds of cookie banners like the Guardian, which disrupt the tool, and header ads (which don't seem to display in some cases anyway and waste height).

image

This is an alternative PR to https://github.com/palewire/news-homepages/pull/10

Partial fix for #4 until you can do some kind of DNS or request-level blocking.

### CODE REVIEW

**Comment by palewire** [comment]
I love the creativity here, but I suspect @simonw would prefer us to refactor to use YAML inputs for this kind of thing. I'm not sure I've made up my mind. Would you prefer if we got rid of the CSVs? This is all rough draft stuff I'm not attached to.

**Comment by MattieTK** [comment]
I think that sounds sensible long term @palewire - yaml loses the readability of the csv for scanning as to what sources are in what groups etc, which is a pain and something I thought of when doing this, but equally I can see how this would get complicated quickly if you wanted to do much more than just removing a few elements, and I would then be on the side of the yaml solution.

**Comment by palewire** [comment]
Here's a dumb idea that might be overcooked. What if we had a folder called `sources` and then the "bundles" were subdirectories and then each site had a yaml file in the subdirectory where they were bundled?

In my addled imagination, that seems like it might solve the problem of keeping the bundles visible, while still getting us to nice clean yaml per site.

**Comment by palewire** [comment]
As I think that idea through, I see that the shot-scraper code does not allow a mix of configuration between YAML and CLI. So I dunno.

**Comment by palewire** [comment]
Okay. I think got this resolved structurally. The shoot.py command now supports optional js files in the `sources/javascript` folder. If a file there exists with the handle of the site being shot, it will be passed along to shot-scraper. Adding a new site just means dropping in a new slugged file there.

I've already done it for LAT

https://github.com/palewire/news-homepages/blob/main/newshomepages/sources/javascript/latimes.js

**Comment by MattieTK** [comment]
Amazing, I was going to have a go at this today but I wake up and you've already got it done! Thanks a lot, I guess we can close this 👍

**Comment by palewire** [comment]
Cool. If you have the time, I could just all the JS whack a mole help I can get.

**Pull request closed without merging**
