### PR TITLE
feat: add washingtonpost to us-national-newspapers

### PR DESCRIPTION
**Pull request by erikreyna**
Adds The Washington Post to US National Newspapers bundle.

washingtonpost

### CODE REVIEW

**Comment by erikreyna** [comment]
@palewire did I do this correctly?

**Comment by palewire** [comment]
I think you got the code right. One problem: washingtonpost.com is consistently timing out for me. Does the `shoot.py` command work for you?

```bash
$ pipenv run python shoot.py single  washingtonpost;                                                                                          
Loading .env environment variables...                                                                                                         
Traceback (most recent call last):                                                                                                            
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/bin/shot-scraper", line 8, in <module>                                
    sys.exit(cli())                                                                                                                           
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1128, in __call__    
    return self.main(*args, **kwargs)                                                                                                         
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/shot_scraper/cli.py", line 162, in shot
    shot = take_shot(context, shot, use_existing_page=use_existing_page)
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/shot_scraper/cli.py", line 469, in take_shot
    page.goto(url)
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 7328, in goto
    self._sync(
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 122, in 
goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39,
 in send
    return await self.inner_send(method, params, False)
  File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63,
 in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.washingtonpost.com/", waiting until "load"
============================================================
```

**Comment by erikreyna** [comment]
The screenshot I posted was from running that command. 

> I think you got the code right. One problem: washingtonpost.com is consistently timing out for me. Does the `shoot.py` command work for you?
> 
> 
> 
> ```bash
> 
> $ pipenv run python shoot.py single  washingtonpost;                                                                                          
> 
> Loading .env environment variables...                                                                                                         
> 
> Traceback (most recent call last):                                                                                                            
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/bin/shot-scraper", line 8, in <module>                                
> 
>     sys.exit(cli())                                                                                                                           
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1128, in __call__    
> 
>     return self.main(*args, **kwargs)                                                                                                         
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1053, in main
> 
>     rv = self.invoke(ctx)
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
> 
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
> 
>     return ctx.invoke(self.callback, **ctx.params)
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/click/core.py", line 754, in invoke
> 
>     return __callback(*args, **kwargs)
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/shot_scraper/cli.py", line 162, in shot
> 
>     shot = take_shot(context, shot, use_existing_page=use_existing_page)
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/shot_scraper/cli.py", line 469, in take_shot
> 
>     page.goto(url)
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 7328, in goto
> 
>     self._sync(
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
> 
>     return task.result()
> 
> File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_page.py", line 487, in goto
> 
>     return await self._main_frame.goto(**locals_to_params(locals()))
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 122, in 
> 
> goto
> 
>     await self._channel.send("goto", locals_to_params(locals()))
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39,
> 
>  in send
> 
>     return await self.inner_send(method, params, False)
> 
>   File "/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63,
> 
>  in inner_send
> 
>     result = next(iter(done)).result()
> 
> playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
> 
> =========================== logs ===========================
> 
> navigating to "https://www.washingtonpost.com/", waiting until "load"
> 
> ============================================================
> 
> ```

**Comment by erikreyna** [comment]
I can dig into it tomorrow.

**Comment by palewire** [comment]
hmm. interesting. maybe just me or some weird reason?

**Comment by erikreyna** [comment]
@palewire not just you. I ran it on a different machine and was able to replicate. I'll need to set up a github actions environment to test this.

Going to keep this PR open and will take some time this weekend to dive into it.

**Comment by palewire** [comment]
How it looked when I tried it again today. 
washingtonpost

**Comment by erikreyna** [comment]
Aside from how long it takes to run, we may or may not need to add a user agent to the request. I think we might need to make a PR over at shot-scraper to be able to pass this along as well.

**Pull request closed without merging**
