### PR TITLE
Show timezone to clarify local time

### PR DESCRIPTION
**Pull request by simonw**
Potential clarification for:
- #82

### CODE REVIEW

**Comment by simonw** [comment]
I have not manually tested this.

**Comment by palewire** [comment]
I like where this going but I don't think the pytz timezone names are humanized enough to publish. What do you think of the idea of adding a new location column similar to the bundle files, which would contain the home city of the publication. Then that could be tweeted.

**Comment by simonw** [comment]
Yeah I love that, much more human friendly. It can tweet "at 12:05pm local time in New York"

**Comment by simonw** [comment]
https://twitter.com/newshomepages/status/1516101217495232529 seems to be doing this already:

> U.K. national news homepages at 6:07 PM in London

**Comment by palewire** [comment]
Yes, the bundles already have that column. We'd just need to add a similar column to the sites file.

**Comment by palewire** [comment]
This was handled in https://github.com/palewire/news-homepages/commit/f33dd10c024b90c25fb14bc49dd6f1c532b9b6ed

**Pull request closed without merging**
