### PR TITLE
Single file html save

### PR DESCRIPTION
**Pull request by alex2awesome**
Added a command-line flags to screenshot.py:

--save_html: gives the option to save a single-page HTML file containing all the assets needed to fully render the page.

### CODE REVIEW

**Comment by palewire** [comment]
What do you think about splitting this out into a separate CLI command? Is there a strong reason why it needs to be forked into the screenshot.py file?

**Comment by alex2awesome** [comment]
i don't have experience with `playwright` but my experience with `selenium` is that it's slow and heavy, thus best to instantiate/load/hit-website only once and then do 2 downstream tasks with it. 

Refactoring to a more modular design (one function/script to load the page, 2 separate ones to screenshot or save html) is possible, just wasn't sure if it's worth it.

what's your primary concern? code readability? single-function design?

**Comment by alex2awesome** [comment]
My intention with the html save here is to only:
* save full-page html for like a handful of sites to collect training data on
* use screenshots and a trained model to scale segmentation to the rest of the sites

**Comment by palewire** [comment]
I'd like to keep the code as streamlined as possible. Would you mind spinning off as separate command?

**Comment by palewire** [comment]
This is now a dupe.

**Pull request closed without merging**
